App\TestBundle\Entity\StagingConfig:
    type: entity
    table: staging_config
    repositoryClass: App\TestBundle\Repository\StagingConfig
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: string
            length: 16
        url:
            type: string
            length: 255
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToOne:
        mainSourceConfig:
            targetEntity: App\TestBundle\Entity\MainSourceConfig
            joinColumn:
                name: main_source_config_id
                referencedColumnName: id
        extraSourceConfig:
            targetEntity: App\TestBundle\Entity\ExtraSourceConfig
            joinColumn:
                name: extra_source_config_id
                referencedColumnName: id
